### ISSUE TITLE
Duplicate rows in variant report

### ISSUE THREAD

**Issue by mbyvcm** [erikwaskiewicz/vcf_parser#7]
Some variants are in the variant file multiple times (the same transcript). See variant 11:534227G>A in 190109_NB551415_0008_AH575TAFXY 17M07273 Lung

**Comment by erikwaskiewicz** [comment]
This is an issue with the VEP version used in the pipeline, which contains duplicate annotations of some variants. The only difference between the duplicates is that for one of them canonical=True. If canonical is removed from the vcf_parse config file then the rows will be identical and the duplicate will be filtered out as part of the program.
