### ISSUE TITLE
Multiallelic sites aren't displayed properly

### ISSUE THREAD

**Issue by erikwaskiewicz** [erikwaskiewicz/vcf_parser#8]
Multiallelic sites include the annotations for each alt allele, but the variant name isn't changed (it includes all alt alleles) so it isn't clear which annotations refer to which alt allele.
Also, there is only one allele frequency annotated to all records, most likely the frequency of the first alt allele.

**Comment by mbyvcm** [comment]
I have addressed this by splitting multiallelic calls using bcftools:
/share/apps/bcftools-distros/bcftools-1.8/bin/bcftools norm -m - "$seqId"_"$sampleId"_filteredStr.vcf.gz | /share/apps/bcftools-distros/bcftools-1.8/bin/bcftools filter -e 'AF < 0.01' > "$seqId"_"$sampleId"_filteredStrLeftAligned.vcf.gz
